### ISSUE TITLE
how to make this work for VS2013?

### ISSUE THREAD

**Issue by ScalletaZ** [stevemk14ebr/PolyHook#13]
`auto GetProtectionObject()
        {
                //Return an object to restore INT3_BP after callback is done
            return finally([&]() {`

'auto' gives error

**Comment by stevemk14ebr** [comment]
You can try to use declytype to replace auto but it will be a pain. This was made for vs2015

**Comment by ScalletaZ** [comment]
just thought you could change a way so that PolyHook would work for all version complier. :)

**Comment by Houd1ny** [comment]
I just removed this function :D

**Comment by Houd1ny** [comment]
But how to rebuild  capstone.lib

**Comment by stevemk14ebr** [comment]
Removing this function is a bad solution, it is required if you use any veh hook types. To compile capstone clone the branch on my profile and follow the build instructions given on the latest capstone web page

**Comment by Houd1ny** [comment]
I have rebuild capstone lib for vs 2013. Remove some features(I just need Detour feature).
So if need just this you could use my fork.
