### ISSUE TITLE
Hook functions that already hook by another program !

### ISSUE THREAD

**Issue by Karaulov** [stevemk14ebr/PolyHook#24]
Please add feature for hook functions that already intercepted by another program.

For example read fist jmp, and just move to address and install hook there. (in loop if possible for unlimited hooks at one address)

This is need for some cases to bypass errors...:) Please...

**Comment by stevemk14ebr** [comment]
https://github.com/stevemk14ebr/PolyHook/issues/4

maybe. In the mean time you can just do setuphook(&target + 0x5,...)
this will skip 5 bytes past the start of the function, replace 0x5 with the size of the hook installed by other programs.

**Comment by Karaulov** [comment]
But i don't know, hooked function or no.
