### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by richard-adlava** [stevemk14ebr/PolyHook#29]
I'm getting a post error:
PolyHook x64Detour: Relocation can be out of range

unsure what would cause this or what it means, could you please clarify?
![image](https://user-images.githubusercontent.com/38365125/40580117-6157a992-6106-11e8-8adb-6c578abde678.png)

**Comment by stevemk14ebr** [comment]
This is a warning that is printed always no matter which function is detoured. There is an unhandled cases where hooking will fail if the function you are hooking is more than 2gb away from the allocated trampoline. From your screen shot that function is fine and will have no issue
