### ISSUE TITLE
Cannot build on Visual Studio 2017

### ISSUE THREAD

**Issue by markhc** [stevemk14ebr/PolyHook#30]
Your modified capstone build was compiled with an older version of the compiler.

The error is:

`Error C1047: The object or library file 'capstone.lib' was created with an older compiler than other objects; rebuild old objects and libraries`

Do you perhaps have the source files for this capstone version that Polyhook is using? The latest versions of capstone are not compatible with your library so this is pretty much unusable right now.

I should clarify that this only happens on Release mode. Debug compiles fine.

**Comment by stevemk14ebr** [comment]
I don't have the exact version but the fork I did was here https://github.com/stevemk14ebr/capstone if you go X number of commits back there's the version I used for this but I'm not sure which exactly TBH. I might update this with the capstone version I used if I get some time just for historical sake. But really I recommend v2, there's alot of issues here

**Comment by stevemk14ebr** [comment]
looking around again, i think this guys fork was at feature parity with the version i used. Also you can use the up to date capstone master and it should work with minimal modifications needed to polyhook. Here's the guys fork if you want to try it: https://github.com/baumane/capstone.

Again though i recommend just using V2, this version is unsupported and is only here for history

**Comment by markhc** [comment]
Alright, fair enough.

Closing this.
